# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Twigs Deployment Staging

on:
  push:
    branches: ["staging"]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      bucket_name: ${{ secrets.AWS_BUCKET_NAME }}

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      
      - name: Installing Dependencies
        run: yarn

      - name: Building Twigs Docs
        run: yarn build:docs
      
      - name: Upload Build to S3
        working-directory: ./packages/docs/
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY_PRODUCTION }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_KEY_PRODUCTION }}
          AWS_DEFAULT_REGION: 'us-east-1'

        run: | 
          aws s3 cp ./docs s3://ss-marketplace-twigs-staging --region us-east-1 --recursive
      