# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Twigs Deployment Staging

on:
  push:
    branches: ["staging"]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      bucket_name: ${{ secrets.AWS_BUCKET_NAME }}

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      
      - name: Installing Dependencies
        run: yarn

      - name: Building Twigs Docs
        run: yarn build:docs
      
      - name: Upload Build to S3
        working-directory: ./packages/docs/
        env:
          aws_access_key_id: ${{ secrets.ACCESS_KEY_PRODUCTION }}
          aws_secret_access_key: ${{ secrets.SECRET_KEY_PRODUCTION }}
          aws_default_region: ${{ secrets.AWS_DEFAULT_REGION }}
          
        run: aws s3 cp build s3://${bucket_name}/ --region ${aws_default_region}
      